name: Deploy To Develop S3

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: 의존성설치
        run: npm install

      - name: 빌드
        run: npm run build

      - name: AWS 인증 절차
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}

      - name: S3 기존 파일들 삭제후 새로 업로드
        run: |
          aws s3 rm --recursive s3://practice-aws-dev
          aws s3 cp ./dist s3://practice-aws-dev/ --recursive

      - name: Cloudfront 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id E39CEWOBL82RQS --paths "/*"
